{
    'name': "Eenadu Multi Delivary Order",
    'version': '16.0.0',
    'category': 'Sales',
    'summary': """ """,
    'description': """
        
    """,
    'depends': ['custom_purchase', 'sale', 'sale_management', 'sale_stock', 'stock', 'contacts', 'web', 'account', 'sales_team'],
    'website': "",
    'data': [
        'security/sales_team_group.xml',
        'security/sales_circulation_groups.xml',
        'security/ir.model.access.csv',
        'views/contact_inherit.xml',
        'views/res_users.xml',
        'views/duplicate_sale_order_line.xml',
        'views/sale_view.xml',
        'views/crm_team.xml',
        'views/agent_report.xml',
        'views/account_move.xml',
        'views/res_district.xml',
        'views/return_stock.xml',
        'views/menu_circulation.xml',
        'views/demand_request.xml',
        'views/schedulars.xml',
        'views/create_payment_dup.xml',
        'views/payment_informations_invoice.xml',
        'views/invoicing_create_payment.xml',
        # 'views/agent_commission.xml',
        'reports/paperformat.xml',
        'reports/delivery_channel_report.xml',
        'reports/report.xml',
        'reports/tax_invoice.xml',
        'reports/eenadu_report.xml',
        'data/email_temp.xml',
        'data/agent_indent_webiste.xml',
        'data/agent_return_webiste.xml',
        'data/agent_invoice_webiste.xml',
        'data/agent_deposit_website.xml',
        'data/demand_request_from.xml',
        'data/return_request_form.xml',
        'views/return_request_view.xml',
        'data/return_request_website.xml',
        'data/demand_request.xml',
        'wizards/internal_order_creating.xml',
        'wizards/agent_invoices_creating.xml',
    ],
        'assets': {
        'web.assets_backend': [
            'sales_circulation/static/src/js/sales_circulation_dashboard.js',
            'sales_circulation/static/src/js/circulation_agent_dashboard.js',
            'sales_circulation/static/src/xml/sales_circulation_dashboard.xml',
            'sales_circulation/static/src/xml/circulation_agent_dashboard.xml',
            # 'sales_circulation/static/src/js/circulation_portal.js',
            'sales_circulation/static/src/js/website_form.js',
            'sales_circulation/static/src/js/return_request.js',
            'sales_circulation/static/src/css/style.css',
            'sales_circulation/static/src/css/stylecirculation1.css',

        ],
        'web.assets_frontend': [
            'sales_circulation/static/src/css/style.css',
            'sales_circulation/static/src/css/stylecirculation1.css',

            # 'sales_circulation/static/src/js/timer.js',
            # 'sales_circulation/static/src/js/circulation_portal.js',
            'sales_circulation/static/src/js/website_form.js',
            'sales_circulation/static/src/js/return_request.js',
        ],

    },
    'qweb': [
        'static/src/xml/*.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
    'sequence': -1,
}
