from . import sale_order
from . import contacts_inherit
from . import agent_report
from . import res_district
from . import return_stock
from . import sales_circulation_dashboard
from . import res_users
from . import account_move
from . import crm_team
from . import demand_request
from . import return_request
from . import cron
from . import schedulars
from . import create_payment_dup
from . import bank_details
from . import agent_commission
from . import hr_employee
